/**
 * Copyright (c) 2015, Václav Vilímek
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 	- Redistributions of source code must retain the above copyright notice, this list 
 * 	  of conditions and the following disclaimer.
 *  - Redistributions in binary form must reproduce the above copyright , this list 
 *    of conditions and the following disclaimer in the documentation and/or other materials 
 *    provided with the distribution.
 *  - Neither the name of the ALLCOMP a.s. nor the of its contributors may be used to endorse 
 *    or promote products from this software without specific prior written permission.
 *    
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL VÁCLAV VILÍMEK BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package cz.allcomp.shs.allcomplib.transducers;

import cz.allcomp.shs.allcomplib.common.Signature;


/**
* transducers/EwcStateSign.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/petr/secret/ewa/AllNet.idl
* Sunday, 15 February 2015 11:26:13 o'clock CET
*/


/** 
  * The <code>EwcStateSign</code> interface defines a values indicating Ewc communication state.
  */
public interface EwcStateSign extends Signature
{

  /** no EWC associated with given address. */
  public static final int UNUSED = (int)(0x6465ED00L);

  /** no EWC responding at given address. */
  public static final int OFFLINE = (int)(0x8FF214E0L);

  /** EWC is enumerated but no software ID is verified. */
  public static final int NO_SW = (int)(0x4800C570L);

  /** EWC is enumerated but no hardware ID is verified.
      * This never occurs normally; it means readdressing in progress.
      */
  public static final int NO_HW = (int)(0x4800C0D7L);

  /** EWC is enumerated but no further data are read. */
  public static final int ONLINE = (int)(0x84214E00L);

  /** EWC works but communication timeouts. */
  public static final int DROPOUT = (int)(0xD98B8630L);

  /** EWC works in emergency communication mode. */
  public static final int WORKING = (int)(0x7890C004L);

  /** EWC works in normal communication mode. */
  public static final int CORRECT = (int)(0xC899EC30L);
} // interface EwcStateSign
